### ISSUE TITLE
Missing x5c field

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/fido-authenticator#1]
While working on the verification feature for pynitrokey I have found that `fido-authenticator` does not return `x5c` field in the response for the credential making. It is present in Nitrokey FIDO2's response though. To investigate and crosscheck with the FIDO specification.

- https://fidoalliance.org/specs/fido-v2.1-rd-20210309/
- https://www.w3.org/TR/webauthn-2/#sctn-packed-attestation-cert-requirements
- https://github.com/Nitrokey/pynitrokey/issues/96

NK3 development firmware, version 0.64.0
Reproduction:
1. Run pynitrokey with the linked patch as:
    `nitropy fido2 verify`

Relevant excerpt:

https://github.com/Nitrokey/fido-authenticator/blob/972b18d4eb224b321b1ed78cfd42ae8374cf9e74/src/lib.rs#L1987-L2001

cc @robin-nitrokey 

PS Ticket should be moved upstream after confirmation

**Comment by robin-nitrokey** [comment]
Cannot reproduce.  Did you setup the FIDO2 certificate on your device?

Production device (firmware v1.0.0):
```
$ nitropy fido2 verify
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
please press the button on your Nitrokey key
Touch your authenticator to generate a credential...
unknown fingerprint! ad8fd1d16f59104b9e06ef323cc03f777ed5303cd421a101c9cb00bb3fdf722d
```

Development device:
```
$ nitropy fido2 verify
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
please press the button on your Nitrokey key
Touch your authenticator to generate a credential...
unknown fingerprint! 44fa598fdc98681dc5c8659a804c40bd6e53f8e54a781608b0651d47a53e1c8a

```

**Comment by robin-nitrokey** [comment]
Caused by missing FIDO2 certificate and key.
