### ISSUE TITLE
CredentialData: (de)serialize `rp` and `user` with `serde_indexed`

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/fido-authenticator#57]
These are currently (de)serialized with the normal `serde` derive implementation, they could instead be made more compact by using a `serde_indexed` approach.

There would be the challenge of needing to either migrate, or to support deserialisation of both approaches.

For many credentials, this should save around 22 bytes of data, or more than a 10% gain.

**Comment by robin-nitrokey** [comment]
In https://github.com/Nitrokey/fido-authenticator/pull/59, we instead implemented serialization using a single character.  This has two advantages:  We can keep compatibility with the existing data and the field order in the code does not affect the serialized format.  The effect should be similar to the serde-indexed solution, so I’m closing this issue.
