### ISSUE TITLE
Pass Google ctap2 test suite

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/fido-authenticator#6]
- [x] make sure that all test cases are executed
  - [x] fix crash for overlong credential ID
    - https://github.com/Nitrokey/fido-authenticator/pull/4
  - [x] `make_credential_option_uv_true`: fix unexpected CBOR response
    - https://github.com/Nitrokey/ctap-types/issues/8
  - [x] `client_pin_general_pin_retries`: refresh auth token failed
    - https://github.com/Nitrokey/fido-authenticator/issues/27
- [x] make all test cases pass
  - [x] Tests bad parameters in RP entity parameter of MakeCredential. (id: make_credential_relying_party_entity) - Optional entry icon not recognized.
    - https://github.com/Nitrokey/ctap-types/issues/3
    - https://github.com/google/CTAP2-test-tool/issues/132
  - [x] Tests credential descriptors in the exclude list of MakeCredential. (id: make_credential_exclude_list_credential_descriptor) - Failure to accept a valid credential descriptor.
    - `EncryptedSerializedCredential` too long (230 bytes ciphertext)
    - https://github.com/Nitrokey/fido-authenticator/issues/29
  - [x] Tests entries in the credential parameters list. (id: make_credential_cred_params) - Accepted unsupported type in credential parameters list.
    - `type` not checked in `makeCredential`
    - cf. spec: *The value SHOULD be a member of [PublicKeyCredentialType](https://www.w3.org/TR/webauthn/#enumdef-publickeycredentialtype) but [client platforms](https://www.w3.org/TR/webauthn/#client-platform) MUST ignore unknown values, ignoring any [PublicKeyCredentialParameters](https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialparameters) with an unknown [type](https://www.w3.org/TR/webauthn/#dom-publickeycredentialparameters-type).*
    - https://github.com/Nitrokey/fido-authenticator/issues/20
  - [x] Tests if non-ASCII display name are accepted. (id: make_credential_non_ascii_display_name) - Failed on displayName with non-ASCII characters.
    - It looks like this is not an issue with non-ASCII characters but with an overlong display name.  We only handle 64 bytes but the test name has 3 * 60 = 180 bytes.  It should therefore be truncated.
    - https://github.com/Nitrokey/ctap-types/issues/4
  - [x] Tests if the resident key option is rejected in GetAssertion. (id: get_assertion_option_rk) - The resident key option (false) was not rejected.
    - https://github.com/Nitrokey/fido-authenticator/issues/23
  - [x] Tests if empty user IDs are omitted in the response. (id: get_assertion_empty_user_id) - The response includes user with an empty ID. This behaviour has known interoperability hurdles.
    - https://github.com/Nitrokey/fido-authenticator/issues/24
  - [x] Tests if PINs are blocked correctly. (id: client_pin_block_pin_retries) - PIN retries did not decrement correctly.
    - This was actually a problem with the test execution because I did not restart the usbip runner during the test.

This PR contain all changes required to achieve the results described above:
- https://github.com/Nitrokey/nitrokey-3-firmware/pull/311

source: https://github.com/Nitrokey/CTAP2-test-tool/tree/docker-build
<del>fix for usbip simulation: https://github.com/Nitrokey/CTAP2-test-tool/tree/nk3-usbip</del>

**Comment by robin-nitrokey** [comment]
@szszszsz The test suite [requires that the response to the authenticatorClientPIN command is empty for the SetPin and ChangePin subcommands](https://github.com/Nitrokey/CTAP2-test-tool/blob/6da335fb08c28c2d1b655789bc2bba3e2d852cfd/src/fido2_commands.cc#L711).  We return an empty map instead (`[0xa0]` in CBOR).  From my understanding, both responses are valid – see [Section 6.5.5. in the spec](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#authnrClientPin-cmd-dfn):  For the command in general, it says “On success, authenticator returns the following structure in its response:”, describing the response map.  For the two subcommands, it just says “returns CTAP2_OK”.

So I would say the proper fix is that the test suite should also accept empty maps.  What is your opinion on this?

**Comment by szszszsz** [comment]
Ha! Good question. Looking into spec indeed it's only returns CTAP2_OK. IMHO I would agree with the test suite assumption, that there is either a correct, filled response or not at all - this makes the empty CBOR array invalid in this case. 

Note: this is not an official FIDO test suite, and things might be different from the official one. Still this test suite feels strict enough, and it's results are taken into consideration for the browser development (if I am not mistaken).

**Comment by robin-nitrokey** [comment]
With https://github.com/Nitrokey/nitrokey-3-firmware/pull/311 (https://github.com/Nitrokey/nitrokey-3-firmware/pull/311/commits/623fad960ce775b1a98cdbbddcd763c593905a5c) we pass 71 of 74 tests using the usbip runner.  The three failed tests are caused by the automatic touch confirmation.

```
RESULTS
Failed test: Tests if user touch is required for MakeCredential. (id: make_credential_physical_presence) - A credential was created without user presence.
A prompt was expected, but not performed. Sometimes it is just not recognized if performed too fast.
Expected error code `CTAP2_ERR_USER_ACTION_TIMEOUT`, got `CTAP2_OK`.
Failed test: Tests if user touch is required for GetAssertion. (id: get_assertion_physical_presence) - A credential was asserted without user presence.
A prompt was expected, but not performed. Sometimes it is just not recognized if performed too fast.
Expected error code `CTAP2_ERR_USER_ACTION_TIMEOUT`, got `CTAP2_OK`.
Failed test: Tests if Reset requirements are enforced. (id: reset_physical_presence) - Reset was allowed without touch.
A prompt was expected, but not performed. Sometimes it is just not recognized if performed too fast.
Expected error code `CTAP2_ERR_USER_ACTION_TIMEOUT`, got `CTAP2_OK`.
Passed 71 out of 74 tests.
To re-run tests that failed, supply the following flag:
--test_ids=make_credential_physical_presence,get_assertion_physical_presence,reset_physical_presence
```

**Comment by robin-nitrokey** [comment]
The three user presence checks that fail with the usbip runner work on real hardware.

**Comment by robin-nitrokey** [comment]
With https://github.com/Nitrokey/nitrokey-3-firmware/pull/314, the user presence checks work in the usbip runner too.

**Comment by robin-nitrokey** [comment]
With https://github.com/trussed-dev/trussed/pull/122 and https://github.com/trussed-dev/usbd-ctaphid/pull/6, the test suite passes on real hardware using the development firmware.  There are still some warnings regarding potentially missing touch confirmations and mismatched error codes.

[results.txt](https://github.com/Nitrokey/fido-authenticator/files/12031172/results.txt)

**Comment by daringer** [comment]
Nice, I can report:

> Passed 74 out of 74 tests.

based on this firmware: https://github.com/Nitrokey/nitrokey-3-firmware/pull/311 using a NK3AM

[result.txt](https://github.com/Nitrokey/fido-authenticator/files/12082068/result.txt)

**Comment by sosthene-nitrokey** [comment]
I did get some errors but I believe they are  related to not pressing when required and vice versa
[results.txt](https://github.com/Nitrokey/fido-authenticator/files/12081961/results.txt)
